---
project-root-path: "/path/to/root/dir"
segmentation-script: "/path/to/segmentation/script.sh"

transfer-model-base-path: "/path/to/transfer/models/root/dir"

images-test-root-path: "/path/to/preprocessed/demo/images/dir"
images-app-root-path: "/path/to/images/in/app/dir"

# available styles (models) 
styles-list:
  - "ArtDeco"
  - "Classic"
  - "Glamour"
  - "Industrial"
  - "Minimalistic"
  - "Modern"
  - "Rustic"
  - "Scandinavian"
  - "Vintage"